import makeWASocket, { Browsers, DisconnectReason, isJidBroadcast, isJidNewsletter, makeCacheableSignalKeyStore, useMultiFileAuthState, fetchLatestBaileysVersion } from '@whiskeysockets/baileys';
import NodeCache from '@cacheable/node-cache';
import pino from 'pino';
import qrcode from 'qrcode-terminal';
import { config, jidToNumber } from './config.js';
import { createCommandHandler } from './commands.js';
import { Store } from './store.js';
import { createHwidService } from './services/hwid.js';

const logger = pino({ level: config.logLevel }); const store = new Store(config.dataFile); const retryCache = new NodeCache({ stdTTL: 600, useClones: false }); const groupCache = new NodeCache({ stdTTL: 300, useClones: false }); const messages = new Map(); const MAX_MESSAGES = 1000; let stopping = false; let reconnectTimer; let activeSocket;
const unwrap = (content) => content?.ephemeralMessage?.message || content?.viewOnceMessage?.message || content?.viewOnceMessageV2?.message || content?.documentWithCaptionMessage?.message || content;
const extractText = (message) => { const c = unwrap(message?.message); return c?.conversation || c?.extendedTextMessage?.text || c?.imageMessage?.caption || c?.videoMessage?.caption || ''; };
function remember(message) { const k = message?.key; if (!k?.remoteJid || !k?.id || !message.message) return; messages.set(`${k.remoteJid}:${k.id}`, message.message); while (messages.size > MAX_MESSAGES) messages.delete(messages.keys().next().value); }
function scheduleReconnect(reason) { if (stopping || reconnectTimer) return; logger.warn({ reason }, 'Programando reconexión'); reconnectTimer = setTimeout(() => { reconnectTimer = undefined; startBot().catch((error) => { logger.error({ err: error }, 'Fallo al reconectar'); scheduleReconnect('fallo durante la reconexión'); }); }, 5000); }
async function startBot() {
  if (stopping) return; await store.init(); const { state, saveCreds } = await useMultiFileAuthState('./.baileys_auth'); const { version } = await fetchLatestBaileysVersion(); const sock = makeWASocket({ version, auth: { creds: state.creds, keys: makeCacheableSignalKeyStore(state.keys, logger) }, logger, browser: Browsers.macOS('Chrome'), markOnlineOnConnect: false, syncFullHistory: false, generateHighQualityLinkPreview: false, connectTimeoutMs: 60_000, defaultQueryTimeoutMs: 60_000, keepAliveIntervalMs: 30_000, retryRequestDelayMs: 5_000, msgRetryCounterCache: retryCache, maxMsgRetryCount: 5, shouldIgnoreJid: (jid) => isJidBroadcast(jid) || isJidNewsletter(jid), getMessage: async (key) => messages.get(`${key.remoteJid}:${key.id}`), cachedGroupMetadata: async (jid) => groupCache.get(jid) }); activeSocket = sock;
  sock.ev.on('creds.update', saveCreds); sock.ev.on('connection.update', ({ connection, lastDisconnect, qr }) => { if (qr) qrcode.generate(qr, { small: true }); if (connection === 'open') logger.info('BRANDON VENTAS conectado a WhatsApp'); if (connection === 'close') { const code = lastDisconnect?.error?.output?.statusCode; const reconnect = !stopping && code !== DisconnectReason.loggedOut; logger.warn({ code, reconnect }, 'Conexión cerrada'); if (reconnect) scheduleReconnect(`cierre ${code || 'desconocido'}`); } });
  sock.ev.on('groups.update', async (events) => { for (const event of events) { try { if (event.id) groupCache.set(event.id, await sock.groupMetadata(event.id)); } catch (error) { logger.debug({ err: error }, 'No se pudo actualizar el grupo'); } } });
  const hwid = createHwidService(config, logger); const handle = createCommandHandler({ store, sock, logger, hwid });
  sock.ev.on('messages.upsert', async ({ messages: incoming, type }) => { for (const message of incoming) remember(message); if (type !== 'notify') return; for (const message of incoming) { try { if (!message.message || message.key.fromMe) continue; const sourceJid = message.key.remoteJid; if (!sourceJid || sourceJid === 'status@broadcast' || sourceJid.endsWith('@broadcast')) continue; const senderJid = message.key.participantAlt || message.key.participant || message.key.remoteJidAlt || sourceJid; const text = extractText(message).trim(); if (!text.startsWith(config.prefix)) { if (text) await handle({ message, text: 'start', senderJid, sourceJid, pushName: message.pushName || jidToNumber(senderJid) }); continue; } await handle({ message, text: text.slice(config.prefix.length), senderJid, sourceJid, pushName: message.pushName || jidToNumber(senderJid) }); } catch (error) { logger.error({ err: error, messageId: message.key?.id }, 'Error procesando mensaje'); } } });
}
async function shutdown(signal) { if (stopping) return; stopping = true; if (reconnectTimer) clearTimeout(reconnectTimer); logger.info({ signal }, 'Apagando bot'); activeSocket?.end?.(new Error(`Shutdown: ${signal}`)); }
process.once('SIGINT', () => shutdown('SIGINT')); process.once('SIGTERM', () => shutdown('SIGTERM')); startBot().catch((error) => { logger.error({ err: error }, 'No fue posible iniciar el bot'); scheduleReconnect('fallo durante el arranque'); });
